---
title: "Factsheet"
author: "Jessica Gephart"
date: "7/13/2020"
output:
  pdf_document: default
  html_document: default
---
## Summary

## Background

High quality catch data is a pillar of fisheries management around the world. Catch data is central to enforcing quota systems and is a critical input to fisheries management models, both to understand the biomass removed from the population and as an indicator of the stock health. While stock assessments remain the gold standard for evaluating the sustainability of a fishery, full stock assessments are cost-prohibitive in many locations and at the frequency necessary. Catch data therefore remains a critical input piece of data for data-poor stock assessment and when paired with with fishing effort, serves as an indicator of catch sustainability (Carruthers et al. 2012). 

Illegal, unreported and underreported (IUU) fishing by its nature results in an underestimate of catch, posing a data and management problem. IUU fishing represents an estimated $10-23.5 billion and 11-26 million tonnes of catch annually, with total catch estimated to be 40% higher in some regions than reported catch (Agnew et al. 2009). In addition to undermining fisheries management, IUU fishing has been associated with human rights abuses, and drug, weapon and wildlife trafficking (Ewell et al. 2017; Chapsos and Hamilton 2019; Miller et al. 2019). 

One issue that can result in an underestimate of catch, therefore resulting in underreported catch or creating a pathway through which other IUU fish can be landed or imported, is through the application of low live weight conversion factors. In general, the weight of fish caught is not measured directly. Instead, catch is typically estimated by multiplying the weight of fish landed, often after some amount of processing (e.g., removal of head or guts) that reduces the weight, by a "live weight conversion factor". For example, 1000 tonnes of landed fish with an associated live weight conversion factor of 1.2 would result in an estimated 1200 tonnes of catch. Converting landings to the live weight equivalent is necessary because patterns in landed weight will vary substantially with differences in processing prior to landing. The resulting live weight equivalent of the landed weight serves as the catch estimate reported in standard international databases. 

Noteably, seemingly small numerical differences in live weight conversion factors can result in large differences in estimated catch. For example, if we take the 1000 tonnes of landed fish from above and instead apply a live weight conversion factor of 1.8, we would estimate 1800 tonnes of catch, or an additional 600 tonnes. As discussed later in this report, live weight conversion factors for a single product can vary substantially more than in this example. Yet, despite the fact that applying different live weight conversion factors will dramatically shift estimated catch, live weight conversion factors are not generally reported alongside estimated catch. Further, once catch is aggregated by species or taxonomic group, the information on processing at landing is lost, making it impossible to reestimate catch using a different set of live weight conversion factors from the catch data alone. As a result unreporeted live weight conversion factors represent a set of critical underlying assumptions in catch data that inhibit data reproducibility and transparency. 

Following the FAO Coordinating Party on Fishery Statistics, within this report, the landed weight refers to the weight of product at the time of landing, regardless of the state (e.g., fresh or frozen) and presentation (e.g., whole, gutted, filleted, etc.), the product weight refers to the weight of a product at the time of weighing, and the nominal catch refers to the landings converted to a live weight basis. Since fishery products can be landed in diverse states and presentations, which dramatically alter the weight, catch statistics are reported as nominal weight in international statistics. In order to convert from landed weight to nominal weight, a live weight conversion factor must be applied. The conversion to nominal weight enables better catch comparison across space and time since it incorporates differences in state and presentation. At the same time, the application of live weight conversion factors can introduce error when the factors do not accurately represent processing losses. Additionally, nominal catch only represents the live weight equivalent of the fishery products landed and therefore cannot be used to directly evaluate the gross catch, which includes not only the retained catch, but also the discarded catch. 

The EU catch certificate program aims to improve catch reporting in order to deter IUU fishing and guarantee that seafood sold within the EU is of legal origin. To improve the catch reporting, the Commission implementing regulation (EU) No 404/2011 outlines which live weight conversion factors should be used for catch landed in or exported to the EU. For landings by Regional Fisheries Management Organizations, of which the EU is a Contracting party or cooperating non-Contracting party, or in areas where the EU has an agreement to fish in third country waters, the conversion factors defined by the Regional Fisheries Management Organization or third-party nation apply. Otherwise, the conversion factors set by the EU are to be used when available. In cases where no EU or regional conversion factors exist for a given species and presentation, the conversion factor adopted by the flag Member State applies. Finally, imported seafood products are subject to a separate set of issues related to live weight conversion factors, stemming from both the different potential set of conversion factors and the fact that the EU cannot generally require non-EU countries to use the conversion factors set by the EU.

## Landings: Impact of conversion factors on catch estimates

## Trade: Impact of conversion factors on catch estimates

## Catch Statistic Terminology

Eurostat, the statistical office of the European Union, houses the catch data within the Agriculture and fisheries division. Eurostat is a member organization of the Coordinating Working Party on Fishery Statistics (CWP) and therefore has adopted the CWP catch statistic concepts and definitions. Therefore, here we compare the terminoligy on the EU catch certificate to the CWP terminology. 

The European Union Catch Certificate includes fields for reporting catch: 

* Catch - Estimated live weight (net fish weight in kg) 
* Catch - Estimated live weight to be landed (net fish weight in kg) 
* Catch - Verified weight landed (net weight in kg) 

The "Catch - Estimated live weight to be landed" field is intended for cases where all fish from one landing is
exported to the EU in one consignment while The "Catch - Estimated live weight" applies to all other situations where, for example, fish is exported live, only part of the landed catch is exported or the flag State processes the product prior to exporting it to the EU. The validating authority of the flag State then completes the “Verified Weight Landed” field, if available.

Within the CWP, net weight refers to the landed weight, not the nominal catch. The EU catch certificate fields "Estimated live weight" and "Estimated live weight to be landed" include estimated live weight (nominal catch) in the main field name, but specify "net fish weight in kg" in the parentheses. This inconsistency in terminology could provide confusion as to whether the field represents nominal catch weight or net weight. 

An additional issue related to the terminology is that the Commission implementing regulation (EU) No 404/2011 states "The fish live weight shall be obtained by multiplying the fish processed weight by the conversion factors referred to in Article 49 of this Regulation for each species and presentation." This guidance includes the the term "fish processed weight," which is not the term used on the catch certificate.

Notably, Amendment 1123 to Regulation (EC) No 1005/2008 Annex II amends the table to replace "Estimated live weight" with "Estimated net weight of fish to be landed," "Estimated live weight to be landed" with "Net fish weight," and "Verified weight landed" with "Verified net fish weight." This amendment resolves the issue of the conflicting simultaneous use of the terms "live weight" and "net weight" in the two certificate fields. At the same time, this seemingly removes the calculation to estimated live weight on the form. This may create an opportunity to centralize and coordinate the application of live weight conversion factors during the processing of the certificate data, but may also may it more difficult to identify the factor applied. 

There are additional terminology issues that arose in this analysis that are not related to the certificate itself, but instead relate to the presentation and state terms. First, there are mismatches between the conversion factor and landings states and presentations, which can introduce potential errors for applying the conversion factors to the landings data. There are even greater inconsistencies between the conversion factor states and presentations and the trade code descriptions. Defining the mapping between these two would reduce the likelihood of an inappropriate conversion factor being applied. Second, as shown in with the comparison to the catch estimates from Norway, the presentation and state specification differs from the EU categorization. Finally, the states and presentations used in the EU are not fully defined, the system is not fully hierarchical, with salted appearing as a state and a presentation, and presentations and states that would apply to trade data are not established (e.g., cooked). 

## Recommendations for Harmonizing Catch Statistics

Reliable catch data is essential for many fishery management and monitoring systems around the world. Catch certificates, including the EU's catch certificate program, represent an important step for tracking catch volumes. In order for the information collected on catch certificates to be maximally valuable, the data processing should be fully reproducible, which includes clafirying certificate terminology (described in the previous section) and reporting live weight conversion factors applied. 

First, the catch certificates should include a field to record the CF value applied. In principle, the conversion factor applied could be derived when both the estimated live weight and the net weight are recorded. Given that the conversion factor represents a critical assumption in the calculation, providing the conversion factor directly would simultaneously make this assumption more transparent and would allow for the live weight calculation to be checked for potential errors. This is especially important in the cases of multiple presentations, where it would be very difficult to guess the conversion factor applied, as the the guidance indicates that "In case of collective presentations, only one conversion factor corresponding to one of the parts of the collective presentation of a fish shall be used."

Second, the live weight converson factors applied to landings data should ideally be reported with the landings data to all data users to convert between the landings and catch data. Catch data is currently aggregated by species, while the landings data is reported by species, presentation, state combinations. Without knowing the live weight conversion factors applied to each species, presentation, state combination, a data user cannot convert between the two data sources. Alternatively, catch data could be reported in terms of the live weight equivalent by species, presentation, state combination, which would allow the apparent live weight conversion factor to be calculated. 

Third, conversion factors should be defined for all landed species, presentation, state combinations and the source of established conversion factors should be specified. As demonstrated in this report, there are substantial data gaps, including cases where a country indicates that the EU-wide value applies, but no EU-wide value is provided. All reported conversion factor data would be improved by presenting the source of the value and the estimated uncertainty in the value. This would enable comparison of values derived from different methods and would contextualize values for fisheries where there may have been changes that affect the conversion factor. Finally, efforts to fill data gaps and update conversion factors should prioritize the values for the most commonly landed and high volume species, presentation, state combinations as these will result in the largest differences in total estimated catch. 